<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.example.Exception" tests="4" time="0.018" ignored="0" failures="0" timestamp="04 Aug 2021 16:27:26 GMT" skipped="0" hostname="LP-PF2YT3M4" errors="0">
  <testcase name="arithmeticException" time="0.002" classname="com.example.Exception"/>
  <testcase name="NullPointerException" time="0.012" classname="com.example.Exception"/>
  <testcase name="testArrayIndexOutOfBound" time="0.002" classname="com.example.Exception"/>
  <testcase name="testStringIndexOut" time="0.002" classname="com.example.Exception"/>
</testsuite> <!-- com.example.Exception -->
